### ISSUE TITLE
We need a protocol to lock control over the robot to one specific controller

### ISSUE THREAD

**Issue by parrottq** [lf-/robotics#9]
If we do not implement some sort of lock, the robot will simultaneously be controlled by two or more different programs.

Goals
- One program controlling robot at once
- Easy way to switch between what is controlling the robot (controller and other programs)
- Programs not controlling may still want feedback from the robot (camera, wheel speed, etc.)

**Comment by lf-** [comment]
This is effectively implemented due to how robotd doesn't make any effort to support multiple connections.
